week3 & week4 tasks - konst
cbanavi/group5_sunshine_weekly_tasks pull request #21
Opened 2024-04-10 20:41 UTC by gavrilov

week3 & week4 tasks

2024-04-12 06:11 UTC, PendarShams commented on src/konst/week4/FrequencyOfCharacters.java
> +    public static String frequencyOfChars(String str) {
Is it better to consider that we might have lower and upper case?

2024-04-12 06:16 UTC, PendarShams commented on src/konst/week3/ReverseNegativeNumbers.java
> +        // Make the number positive for reversing
it might be better to change the int to long to handle the overflow better!

2024-04-12 06:22 UTC, PendarShams requested changes
please check the comments

2024-04-13 02:00 UTC, PendarShams commented on src/konst/week4/FrequencyOfCharacters.java
> +    public static String frequencyOfChars(String str) {
ok thank you

2024-04-13 02:02 UTC, PendarShams approved these changes

2024-04-13 03:03 UTC, Sandzhar98 approved these changes
lgtm

2024-04-13 03:03 UTC, merged