completed April 24th
cbanavi/group5_sunshine_weekly_tasks pull request #25
Opened 2024-04-15 23:25 UTC by PendarShams

2024-04-15 23:30 UTC, cbanavi requested changes

2024-04-15 23:30 UTC, cbanavi commented on src/PenTasks/Week03/ReversedNegativeNumbers.java
You can keep this negative but lgtm

2024-04-15 23:30 UTC, cbanavi commented on src/PenTasks/Week03/PrimeNumber.java
This is returning me 5 is not a prime number

2024-04-15 23:39 UTC, cbanavi requested changes

2024-04-15 23:39 UTC, cbanavi commented on src/PenTasks/Week03/PrimeNumber.java
Now it's telling me basically all numbers are prime

2024-04-15 23:54 UTC, PendarShams commented on src/PenTasks/Week03/PrimeNumber.java
> +        } else if (num % num == 0) {
corrected

2024-04-16 19:35 UTC, cbanavi requested changes
Minor changes

2024-04-16 19:35 UTC, cbanavi commented on src/PenTasks/Week03/ArmstrongNumbers.java
This isn't returning true or false, just the print statement.

2024-04-16 19:35 UTC, cbanavi commented on src/PenTasks/Week03/PrimeNumber.java
lgtm

2024-04-16 19:35 UTC, cbanavi commented on src/PenTasks/Week03/ReversedNegativeNumbers.java
lgtm

2024-04-18 05:16 UTC, cbanavi approved these changes
lgtm

2024-04-18 05:16 UTC, merged