week01 tasks created
cbanavi/group5_sunshine_weekly_tasks pull request #9
Opened 2024-03-28 05:48 UTC by Faranak36

please review.

2024-03-28 16:38 UTC, cbanavi commented on src/faranak/DivisionWithoutOperator_faranak.java
Please fix to where you can divide by negative, you just can't divide by 0

2024-03-28 16:41 UTC, cbanavi requested changes
For DivisionWithoutOperator, please fix to accept negative numbers. Only error should be that it can't be divided by 0.

2024-03-28 16:41 UTC, cbanavi commented on src/faranak/FINRA.java
lgtm!

2024-03-28 16:41 UTC, cbanavi commented on src/faranak/OddOrEven.java
lgtm

2024-03-28 17:26 UTC, Faranak36 commented on src/faranak/DivisionWithoutOperator_faranak.java
oh you're right

2024-03-28 19:42 UTC, cbanavi requested changes
Please review request, sorry for being nit picky. It gave me 0 when n1 was negative. It also gave me 0 when both n1 and n2 are negative.

2024-03-28 19:42 UTC, cbanavi commented on src/faranak/DivisionWithoutOperator_faranak.java
Doesn't work when n1 is negative. Also doesn't work when n1 and n2 are both negative.

2024-03-29 01:43 UTC, jenneft commented on src/faranak/DivisionWithoutOperator_faranak.java
The check for n1 == 0 is unnecessary since any number divided by a non-zero number is valid, including zero. This simplifies the method and focuses on the critical error condition which is dividing by zero.The essential check is that n2 should not be zero.
Remove the unnecessary check for n1 == 0.

Also, implement a correct handling mechanism for cases where n1 is negative to avoid incorrect results or infinite loops.

2024-03-29 01:46 UTC, jenneft commented on src/faranak/FINRA.java
Effective solution.

2024-03-29 01:46 UTC, jenneft commented on src/faranak/OddOrEven.java
Nice work!

2024-03-29 01:47 UTC, jenneft requested changes
DivisionWithoutOperator needs adjustments.

2024-03-29 03:08 UTC, Faranak36 commented on src/faranak/DivisionWithoutOperator_faranak.java
sure I'll work on it

2024-03-29 15:10 UTC, jenneft commented on src/faranak/DivisionWithoutOperator_faranak.java
Hello! Your method Math.floorDiv(a, b) internally uses the division operator to perform the operation. If your goal is to truly avoid using the division operator at all, then you would need a different approach, such as iterative subtraction or a bitwise method.

2024-03-29 15:12 UTC, jenneft approved these changes
Math.floorDiv does not avoid the division operator.
Hint: to implement division without using the division operator, you might consider a method that subtracts the divisor from the dividend until the remainder is less than the divisor.

2024-03-29 15:15 UTC, jenneft requested changes
Math.floorDiv does not avoid the division operator.
Hint: to implement division without using the division operator, you might consider a method that subtracts the divisor from the dividend until the remainder is less than the divisor.

2024-04-01 17:10 UTC, jenneft commented on src/faranak/DivisionWithoutOperator_faranak.java
This version is more straightforward and effective for its intended use case.

2024-04-01 17:10 UTC, jenneft approved these changes

2024-04-01 20:54 UTC, cbanavi approved these changes
lgtm

2024-04-01 20:54 UTC, merged